In [1]:
import numpy as np

In [ ]:
array_1d = np.array([1,2,3,4,5])
print(array_1d.ndim)
print(array_1d.shape)
array_1d
# Lista de Dados, como séries temporais opu coleções de valores

1
(5,)


array([1, 2, 3, 4, 5])

In [ ]:
array_2d = np.array([[1,2,3], [4,5,6]])
print(array_2d.ndim)
print(array_2d.shape)
array_2d
#Matrizes, tabelas de dados, imagens em escala de cinza

2
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_3d = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(array_3d.ndim)
print(array_3d.shape)
array_3d
#Imagens em cores (cada matriz representando um canal de cor, como RGB)

3
(1, 4, 2)


array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [10]:
array_4d = np.zeros((2,3,4,5))
print(array_4d.ndim)
print(array_4d.shape)
array_4d

4
(2, 3, 4, 5)


array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])