In [1]:
import numpy as np

In [5]:
array = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])
print(array.ndim)
print(array.shape)
array

2
(3, 3)


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [6]:
# Buscar elementos na linha 1 e colunas 2
elemento = array[1,2]
elemento

np.int64(60)

In [7]:
#Pegar dados de primeira linha 
linha_0 = array[0]
linha_0

array([10, 20, 30])

In [9]:
#Acessando coluna 1
coluna_0 = array[:, 0]
coluna_0

array([10, 40, 70])

In [ ]:
#Fatiamento para obter um subarray
#Linha 0 a 1 / Coluna 1 a 2
subarray = array[0:2, 1:3]
subarray

array([[20, 30],
       [50, 60]])

In [12]:
mascara = array > 50
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [13]:
elementos_maiores_que_50 = array[mascara]
elementos_maiores_que_50

array([60, 70, 80, 90])

In [14]:
#Modificando elemento na linha 1, coluna 1
array [1,1] = 100
array

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])